#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# context-pull.sh
# Extract backend code context for frontend Claude sessions
# ============================================================

usage() {
    cat <<EOF
Usage: ./context-pull.sh <backend-repo-path> [options]

Extracts relevant backend files into a condensed context document
for use in frontend Claude Code sessions.

Options:
  --output, -o PATH     Output file (default: .claude/backend-context.md)
  --apps, -a APPS       Comma-separated Django app names to include (default: all)
  --include, -i GLOBS   Additional file patterns to include
  --help, -h            Show this help

Examples:
  ./context-pull.sh ../backend-api
  ./context-pull.sh ../backend-api --apps users,products
  ./context-pull.sh ../backend-api --output docs/backend-context.md
EOF
    exit 1
}

# ---- Parse args ----

BACKEND_PATH=""
OUTPUT=".claude/backend-context.md"
APPS=""
EXTRA_INCLUDES=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output|-o)  OUTPUT="$2"; shift 2 ;;
        --apps|-a)    APPS="$2"; shift 2 ;;
        --include|-i) EXTRA_INCLUDES="$2"; shift 2 ;;
        --help|-h)    usage ;;
        -*)           echo "Unknown option: $1"; usage ;;
        *)            BACKEND_PATH="$1"; shift ;;
    esac
done

if [[ -z "$BACKEND_PATH" ]]; then
    echo "Error: backend repo path required"
    usage
fi

if [[ ! -d "$BACKEND_PATH" ]]; then
    echo "Error: $BACKEND_PATH is not a directory"
    exit 1
fi

# ---- Extract files ----

# Default patterns to look for in Django projects
PATTERNS=(
    "*/serializers.py"
    "*/serializers/*.py"
    "*/views.py"
    "*/views/*.py"
    "*/urls.py"
    "*/models.py"
    "*/models/*.py"
    "*/permissions.py"
)

OUTPUT_DIR="$(dirname "$OUTPUT")"
mkdir -p "$OUTPUT_DIR"

{
    echo "# Backend Context"
    echo ""
    echo "> Auto-generated by context-pull.sh on $(date -Iseconds)"
    echo "> Source: $BACKEND_PATH"
    echo ""

    for pattern in "${PATTERNS[@]}"; do
        # Find matching files
        while IFS= read -r -d '' file; do
            # Filter by app if specified
            if [[ -n "$APPS" ]]; then
                local_path="${file#$BACKEND_PATH/}"
                app_name="$(echo "$local_path" | cut -d'/' -f1)"
                if ! echo ",$APPS," | grep -q ",$app_name,"; then
                    continue
                fi
            fi

            rel_path="${file#$BACKEND_PATH/}"
            echo "## \`$rel_path\`"
            echo ""
            echo '```python'
            cat "$file"
            echo '```'
            echo ""
        done < <(find "$BACKEND_PATH" -path "$pattern" -not -path "*/migrations/*" -not -path "*/__pycache__/*" -not -path "*/venv/*" -not -path "*/.venv/*" -print0 2>/dev/null)
    done

    # Integration summaries if they exist
    if [[ -d "$BACKEND_PATH/docs/integration" ]]; then
        echo "---"
        echo "## Integration Summaries"
        echo ""
        for summary in "$BACKEND_PATH"/docs/integration/*.md; do
            [[ -f "$summary" ]] || continue
            echo "### $(basename "$summary" .md)"
            echo ""
            cat "$summary"
            echo ""
        done
    fi

} > "$OUTPUT"

echo "✓ Backend context extracted to $OUTPUT"
echo "  Include $(wc -l < "$OUTPUT" | tr -d ' ') lines from $(find "$BACKEND_PATH" -name "*.py" -path "*/serializers*" -o -name "*.py" -path "*/views*" -o -name "*.py" -path "*/models*" | wc -l | tr -d ' ') files"
